svg import failure
-mooved logo and bg images to assets
known bug:
- import failes with error:
  SyntaxError: The requested module '/src/assets/finike-quiz.svg?import'
  does not provide an export named 'ReactComponent'